---
# Default variables for k3s_agent role
# These can be overridden in inventory, group_vars, or host_vars

k3s_install_url: "https://get.k3s.io"
k3s_channel: "stable"
k3s_version: ""
k3s_service_name: "k3s-agent"
k3s_config_dir: "/etc/rancher/k3s"
k3s_install_dir: "/usr/local/bin"
k3s_master_url: "https://{{ hostvars[groups['masters'][0]]['ansible_host'] }}:6443"
k3s_token_src_on_master: "/home/vagrant/k3s_token"
kubeconfig_path: "/home/vagrant/kubeconfig"
node_type: "worker" # or "edge"
