apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: host-only-net
  namespace: default
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "master": "enp0s8",
    "mode": "bridge",
    "ipam": {
      "type": "host-local",
      "subnet": "192.168.56.0/24",
      "rangeStart": "192.168.56.200",
      "rangeEnd": "192.168.56.250"
    }
  }'