---
# Default variables for k3s_edge role

# K3s installation
k3s_install_url: "https://get.k3s.io"
k3s_channel: "stable"
k3s_version: ""
k3s_install_dir: "/usr/local/bin"
k3s_service_name: "k3s-agent"

# K3s master connection
k3s_master_url: "https://{{ hostvars[groups['masters'][0]]['ansible_host'] }}:6443"

# K3s agent arguments
k3s_agent_args:
  - "--node-name={{ inventory_hostname }}"
  - "--node-ip={{ ansible_host }}"
  - "--kubelet-arg=node-labels=node-type=edge"