# File: kubeadm-join-config.yaml
apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
# Indirizzo del master a cui fare il join
discovery:
  bootstrapToken:
    # Sostituisci con il token generato da 'kubeadm init'
    apiServerEndpoint: "192.168.56.11:6443"
    token: "ie6mjl.jqf3bb4t838g81zl" 
    # Sostituisci con l'hash generato da 'kubeadm init'
    caCertHashes:
      - "sha256:72e9c2e911395264c0338417a529ca6231b3dc9d32c102789d4a99f07758325b"
# Questa Ã¨ la parte cruciale per il worker
nodeRegistration:
  kubeletExtraArgs:
    # USA L'IP DI QUESTO SPECIFICO WORKER!
    node-ip: "192.168.56.12"