# /vagrant/kubernetes/open5gs-core-values.yaml

# Abilita tutti i componenti del core 5G SA
amf:
  service:
    n2:
      nodePort: 30502
nrf:
  enabled: true
scp:
  enabled: true
smf:
  config:
    smf:
      info:
        s_nssai:
          - sst: 1
            sd: "000001"
      # Configura l'SMF per conoscere sia l'UPF del core sia quello del MEC
      pfcp:
        client:
          upf:
            - addr: open5gs-core-upf-svc
              dnn: internet
            - addr: open5gs-mec-upf-svc
              dnn: edge-video
webui:
  service:
    type: NodePort
    nodePort: 30500
populate:
  enabled: true
  # Dati dell'utente di test
  subscribers:
    - imsi: "208930000000001"
      msisdn: "123456789"
      imeisv: "111111111111111"
      key: "0C0A34601D4F07677303652C0462535B"
      opc: "63bfa50ee6523365ff14c1f45f88737d"
      ambr_dl: 1000
      ambr_ul: 1000
      sst: 1
      sd: "000001"
      dnn:
        - name: internet
        - name: edge-video

# Configurazione di MongoDB per usare il provisioner locale
mongodb:
  persistence:
    enabled: true
    storageClassName: "local-path"
    size: 2Gi