# /vagrant/kubernetes/open5gs-mec-values.yaml

amf: { enabled: false }
ausf: { enabled: false }
bsf: { enabled: false }
nrf: { enabled: false }
nssf: { enabled: false }
pcf: { enabled: false }
smf: { enabled: false }
udm: { enabled: false }
udr: { enabled: false }
webui: { enabled: false }
populate: { enabled: false }
scp: { enabled: false }

upf:
  enabled: true
  # La sezione nodeAffinity Ã¨ stata rimossa per semplificare il deployment iniziale.

mongodb:
  persistence:
    storageClassName: "local-path"