---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ueransim-ueransim-gnb
  namespace: "open5gs"
data:
  gnb.yaml: |
    mcc: '208'
    mnc: '93'
    nci: '0x000000010'
    idLength: 32
    tac: 1
    linkIp: 192.168.56.14
    ngapIp: 192.168.56.14
    gtpIp: 192.168.56.14
    amfConfigs:
      - address: open5gs-amf-ngap
        port: 38412
    slices:
      - sst: 1
        sd: "000001"
    ignoreStreamIds: true
---
apiVersion: v1
kind: Service
metadata:
  name: ueransim-gnb-svc
  namespace: "open5gs"
spec:
  clusterIP: None
  selector:
    app: ueransim-gnb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ueransim-ueransim-gnb
  namespace: "open5gs"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ueransim-gnb
  template:
    metadata:
      labels:
        app: ueransim-gnb
    spec:
      nodeSelector:
        "topology.kubernetes.io/zone": ran
      containers:
        - name: gnodeb
          image: docker.io/gradiant/ueransim:3.2.6
          imagePullPolicy: Always
          command: ["/ueransim/build/nr-gnb"]
          args:
            - "-c"
            - "/etc/ueransim/gnb.yaml"
          securityContext:
            privileged: true
          volumeMounts:
            - name: config
              mountPath: /etc/ueransim/gnb.yaml
              subPath: "gnb.yaml"
      volumes:
        - name: config
          configMap:
            name: ueransim-ueransim-gnb