# ansible/kubeadm-config.yaml (Invariato)
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "192.168.56.11"
  bindPort: 6443
nodeRegistration:
  criSocket: "unix:///var/run/containerd/containerd.sock"
  kubeletExtraArgs:
    node-ip: "192.168.56.11"
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: "v1.30.3"
controlPlaneEndpoint: "192.168.56.11:6443"
networking:
  podSubnet: "10.244.0.0/16" # Richiesto da Flannel