apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-video-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-video-analyzer
  template:
    metadata:
      labels:
        app: ai-video-analyzer
    spec:
      nodeSelector:
        "topology.kubernetes.io/zone": edge
      containers:
      - name: yolov5
        image: ultralytics/yolov5:latest
        command: ["python", "detect.py", "--source", "rtsp://rtsp-streamer-svc:8554/stream"]
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "sleep 15"]