db_uri: mongodb://mongodb:27017/open5gs
logger:
  file:
    path: /open5gs/install/var/log/open5gs/ausf.log

global:
  max:
    ue: 1024

ausf:
  sbi:
    server:
      - address: 0.0.0.0
        port: 7777
    client:
      nrf:
        - uri: http://nrf:7777
  metrics:
    server:
      - address: 0.0.0.0
        port: 9090
