db_uri: mongodb://mongodb:27017/open5gs
logger:
  file:
    path: /open5gs/install/var/log/open5gs/nssf.log
  level: info
nssf:
  sbi:
    server:
      - address: 0.0.0.0
        port: 7777
        advertise: nssf
    client:
      nrf:
        - uri: http://nrf:7777
      nsi:
        - uri: http://nrf:7777
          s_nssai:
            sst: 1
            sd: 000001
        - uri: http://nrf:7777
          s_nssai:
            sst: 2
            sd: 000001
    no_tls: true