db_uri: mongodb://mongodb:27017/open5gs
logger:
  file:
    path: /open5gs/install/var/log/open5gs/smf.log
  level: info
smf:
  sbi:
    server:
      - address: 0.0.0.0
        port: 7777
        advertise: smf
    client:
      nrf:
        - uri: http://nrf:7777
    no_tls: true
  pfcp:
    server:
      - address: {{ smf_n4_ip }}  # SMF su n4
        port: 8805
    client:
      upf:
        - address: {{ upf_cloud_n4_ip }}  # N4 upf-cloud
          dnn: internet
  gtpc:
    server:
      - address: {{ smf_n4_ip }}
  gtpu:
    server:
      - address: {{ smf_n4_ip }}
  session:
    - subnet: 10.45.0.0/16
      gateway: 10.45.0.1
      dnn: internet
  dns:
    - 8.8.8.8
    - 8.8.4.4
    - 2001:4860:4860::8888
    - 2001:4860:4860::8844
  mtu: 1400
