db_uri: mongodb://mongodb:27017/open5gs
logger:
  file:
    path: /open5gs/install/var/log/open5gs/smf.log
smf:
  sbi:
    server:
      - address: 0.0.0.0
        port: 7777
    client:
      nrf:
        - uri: http://nrf:7777
  pfcp:
    server:
      - address: 10.204.0.100  # SMF su n4
        port: 8805
    client:
      upf:
        - address: 10.204.0.101  # N4 upf-edge
          dnn: internet
        - address: 10.204.0.102  # N4 upf-cloud
          dnn: mec
  gtpc:
    server:
      - address: 10.204.0.100
  gtpu:
    server:
      - address: 10.204.0.100
  session:
    - subnet: 10.45.0.0/16
      gateway: 10.45.0.1
      dnn: internet
    - subnet: 10.46.0.0/16
      gateway: 10.46.0.1
      dnn: mec
  dns:
    - 8.8.8.8
    - 8.8.4.4
    - 2001:4860:4860::8888
    - 2001:4860:4860::8844
  mtu: 1400
