db_uri: mongodb://mongodb:27017/open5gs
logger:
  file:
    path: /open5gs/install/var/log/open5gs/udr.log
udr:
  sbi:
    server:
      - address: 0.0.0.0
        port: 7777
        advertise: udr
    client:
      nrf:
        - uri: http://nrf:7777
    no_tls: true
  metrics:
    server:
      - address: 0.0.0.0
        port: 9090
