logger:
  file:
    path: /open5gs/install/var/log/open5gs/upf-cloud.log
  level: info
upf:
  pfcp:
    server:
      - address: {{ upf_cloud_n4_ip }}
        port: 8805
  gtpu:
    server:
      - address: {{ upf_cloud_n3_ip }}
  session:
    - subnet: 10.45.0.0/16
      gateway: 10.45.0.1
      dnn: internet
      dev: ogstun
  metrics:
    server:
      - address: {{ upf_cloud_n4_ip }}
        port: 9090
