logger:
  file:
    path: /open5gs/install/var/log/open5gs/upf-edge.log
  level: info
upf:
  pfcp:
    server:
      - address: {{ upf_edge_n4_ip }}
        port: 8805
  gtpu:
    server:
      - address: {{ upf_edge_n3_ip }}
  session:
    - subnet: 10.46.0.0/16
      gateway: 10.46.0.1
      dnn: mec
      dev: ogstun
  metrics:
    server:
      - address: {{ upf_edge_n4_ip }}
        port: 9090
