logger:
  file:
    path: /open5gs/install/var/log/open5gs/upf-edge.log
upf:
  pfcp:
    server:
      - address: 10.204.0.101
        port: 8805
  gtpu:
    server:
      - address: 10.204.0.101
  session:
    - subnet: 10.46.0.0/16
      gateway: 10.46.0.1
      dnn: mec
      dev: ogstun
  metrics:
    server:
      - address: 10.204.0.101
        port: 9090
