logger:
  file:
    path: /open5gs/install/var/log/open5gs/upf-cloud.log
upf:
  pfcp:
    server:
      - address: 10.204.0.102
        port: 8805
  gtpu:
    server:
      - address: 10.204.0.102
  session:
    - subnet: 10.45.0.0/16
      gateway: 10.45.0.1
      dnn: internet
      dev: ogstun
  metrics:
    server:
      - address: 10.204.0.102
        port: 9090
