mcc: '001'
mnc: '01'
nci: '0x000000010'
idLength: 32
tac: 1
linkIp: 0.0.0.0
ngapIp: 0.0.0.0
gtpIp: 0.0.0.0
gtpPort: 2152
ngapPort: 38412
amfConfigs:
  - address: 10.202.0.100
    port: 38412
slices:
  - sst: 1
    sd: 1
  - sst: 2
    sd: 1
ignoreStreamIds: true
